# Generated by Django 5.1.1 on 2024-11-12 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodeguero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('cantidad', models.FloatField()),
                ('unidadMedida', models.CharField(choices=[('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro')], max_length=5)),
                ('estadoMateria', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('contraseña', models.CharField(max_length=10)),
                ('rol', models.CharField(max_length=30)),
                ('estadoUsuario', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.FloatField(default=1)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSoft.materiaprima')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('cantidad', models.IntegerField()),
                ('estadoProducto', models.BooleanField(default=True)),
                ('composicion', models.ManyToManyField(related_name='productos', through='AppSoft.ProductoMateria', to='AppSoft.materiaprima')),
            ],
        ),
        migrations.AddField(
            model_name='productomateria',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSoft.productos'),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('lote', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.FloatField()),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppSoft.materiaprima')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSoft.proveedores')),
            ],
        ),
    ]
