# Generated by Django 5.1 on 2024-11-17 21:01

import AppSoft.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSoft', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productomateria',
            name='cantidad_usada',
        ),
        migrations.AddField(
            model_name='productomateria',
            name='cantidad_utilizada',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='rut',
            field=models.CharField(default=1, max_length=10, unique=True, validators=[AppSoft.models.validar_rut]),
            preserve_default=False,
        ),
    ]
