# Generated by Django 5.1 on 2024-10-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSoft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('contraseña', models.CharField(max_length=10)),
                ('rol', models.CharField(max_length=30)),
                ('estadoUsuario', models.BooleanField()),
            ],
        ),
    ]
