# Generated by Django 5.1.1 on 2024-11-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSoft', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productomateria',
            name='cantidad_usada',
        ),
        migrations.AddField(
            model_name='productomateria',
            name='cantidad_utilizada',
            field=models.FloatField(default=0),
        ),
    ]
