# Generated by Django 5.1 on 2024-11-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSoft', '0002_remove_productomateria_cantidad_usada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
