# Generated by Django 5.1 on 2024-11-06 01:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSoft', '0003_compra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='precio',
            new_name='lote',
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
