# Generated by Django 5.1 on 2024-11-06 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSoft', '0004_rename_precio_compra_lote_compra_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiaprima',
            name='cantidad',
        ),
    ]
