# Generated by Django 5.1 on 2024-11-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSoft', '0005_remove_materiaprima_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='estadoMateria',
            field=models.BooleanField(default=True),
        ),
    ]
