# Generated by Django 5.1 on 2024-11-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSoft', '0006_alter_materiaprima_estadomateria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estadoUsuario',
            field=models.CharField(max_length=25),
        ),
    ]
