# Generated by Django 5.1 on 2024-11-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSoft', '0007_alter_usuario_estadousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='cantidad',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
