# Generated by Django 5.1 on 2024-11-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSoft', '0008_materiaprima_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
