# Generated by Django 5.1 on 2024-11-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSoft', '0012_alter_compra_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='composicion',
            field=models.ManyToManyField(related_name='productos', to='AppSoft.materiaprima'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='estadoProducto',
            field=models.BooleanField(default=True),
        ),
    ]
