# Generated by Django 5.1.1 on 2024-11-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSoft', '0013_productos_composicion_alter_productos_estadoproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodeguero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=12)),
            ],
        ),
    ]
