# Generated by Django 5.1 on 2024-11-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSoft', '0014_bodeguero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodeguero',
            name='contacto',
            field=models.CharField(max_length=16),
        ),
    ]
