# Generated by Django 5.1.1 on 2024-11-11 06:58

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('AppSoft', '0015_alter_bodeguero_contacto'),  # Dependencia de la migración anterior
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoMateria',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('producto', models.ForeignKey(on_delete=models.CASCADE, to='AppSoft.Productos')),
                ('materia', models.ForeignKey(on_delete=models.CASCADE, to='AppSoft.MateriaPrima')),
                ('cantidad_usada', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='composicion',
            field=models.ManyToManyField(through='AppSoft.ProductoMateria', to='AppSoft.MateriaPrima'),
        ),
    ]
