# Generated by Django 5.1.1 on 2024-11-11 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSoft', '0015_alter_bodeguero_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.FloatField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSoft.materiaprima')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSoft.productos')),
            ],
        ),
        migrations.AlterField(
            model_name='productos',
            name='composicion',
            field=models.ManyToManyField(related_name='productos', through='AppSoft.ProductoMateria', to='AppSoft.materiaprima'),
        ),
    ]
