# Generated by Django 5.1.1 on 2024-11-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSoft', '0016_auto_20241111_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productomateria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='composicion',
            field=models.ManyToManyField(related_name='productos', through='AppSoft.ProductoMateria', to='AppSoft.materiaprima'),
        ),
    ]
