# Generated by Django 5.1 on 2024-11-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSoft', '0017_alter_productomateria_id_alter_productos_composicion'),
        ('AppSoft', '0017_auto_20241111_0356'),
    ]

    operations = [
    ]
