# Generated by Django 5.1 on 2024-11-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSoft', '0018_merge_20241111_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='unidadMedida',
            field=models.CharField(choices=[('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro')], max_length=5),
        ),
        migrations.AlterField(
            model_name='productomateria',
            name='cantidad_usada',
            field=models.FloatField(default=1),
        ),
    ]
