# Generated by Django 5.1 on 2024-11-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSoft', '0019_alter_materiaprima_unidadmedida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
